config/routes.rb
Rails.application.routes.draw do
  resources :images do
    member do
      get 'like' => 'images#like'
    end
  end

  get 'search' => 'images#search'
  resources :categories
  resources :users do
    member do
      get 'follow' => 'users#follow'
      get 'collection' => 'users#collection'
      get 'about' => 'users#about'
      get 'followers' => 'users#followers'
      get 'followings' => 'users#followings'
    end
  end
  resources :comments, only: [:create] do
    member do
      get 'reply', to: 'comments#new_reply'
      post 'reply', to: 'comments#create_reply'
    end
  end

  root 'welcome#popular'
  get 'popular' => 'welcome#popular'
  get 'upcoming' => 'welcome#upcoming'
  get 'photos_of_days' => 'welcome#photos_of_days'
  get 'photos_of_months' => 'welcome#photos_of_months'

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :images

  before_save { self.email = email.downcase }

  validates :username, presence: true, length: { maximum: 50 }, format: { with: /\A[a-zA-Z0-9]+\Z/ }, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, presence:true, length: { minimum: 6 }

  def total_images
    Image.where(user: self).count
  end

  def followed?(current_user)
    Follow.where(user: current_user, follow_id: self.id).count > 0
  end

  def count_followers
    Follow.where(follow_id: self.id).count
  end

  def liked?(image)
    Liked.where(user: self, image: image).count > 0
  end

  def avatar_url
    if self.avatar != ''
      self.avatar
    else
      'http://photos.pashadelic.com/user/image/129369/mit.jpeg'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :follow, :about, :collection, :followers, :followings]

  def index
    @users = User.all
  end

  def show
    @images = Image.where(user: @user)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  def follow
    respond_to do |format|
      if current_user
        if @user.followed?(current_user)
          Follow.where(user: current_user, follow_id: @user.id).first.destroy
        else
          @follow = Follow.create(user:current_user, follow_id: @user.id)
          @follow.save
        end
        format.js
      else
        format.js {render inline: 'alert("you must sign in before follow someone!!");'}
      end
    end
  end


  def collection
    #write somethings
  end

  def about
  end

  def followers
    @followers = Follow.where(follow_id: @user.id)
  end

  def followings
    @followings = Follow.where(user: @user)
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :visible, :admin, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def followers_users_list(followers)
    users = []
    followers.each do |follower|
      users << follower.user
    end
    users
  end

  def followings_users_list(followers)
    users = []
    followers.each do |follower|
      users << User.find(follower.follow_id)
    end
    users
  end
end

app/views/users/_follow_button.html.erb
<div id="follow-button-<%= user.id %>">
  <% if user.followed?(current_user) %>
      <%= link_to 'following', follow_user_path(user), remote: true, class:'button-follow' %>
  <% else %>
      <%= link_to 'follow', follow_user_path(user), remote: true, class:'button-follow' %>
  <% end %>
</div>

app/views/users/_follower_list.html.erb
<div class="followers-content">
  <% users.each do |user| %>
      <div class="col col-lg-6">
        <div class="row">
          <div class="user-avatar col-md-4">
            <%= image_tag(user.avatar_url) %>
          </div>
          <div class="user-name col-md-8">
            <%= render 'follow_button', user: user %>
            <p><%= link_to user.name, user_path(user) %></p>
            <%= user.total_images.to_s + ' photos | ' + user.count_followers.to_s + ' follow' %>
          </div>
        </div>

        <div class="row six-images-list">
          <% six_images(user).each do |image| %>
              <%= link_to image_tag(image.img_url.thumb.url), image_path(image) %>
          <% end %>
        </div>
      </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_for(@user) do |f| %>
        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="field">
          <%= f.label :username %><br>
          <%= f.text_field :username, class: 'form-control' %>
        </div>
        <div class="field">
          <%= f.label :email %><br>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <% if @user != User.new %>
            <div class="field">
              <%= f.label :avatar %><br>
              <%= f.text_field :avatar, class: 'form-control' %>
            </div>
        <% end %>
        <div class="field">
          <%= f.label :password %><br>
          <%= f.text_field :password, class: 'form-control' %>
        </div>
        <div class="field">
          <%= f.label :password_confirmation %><br>
          <%= f.text_field :password_confirmation, class: 'form-control' %>
        </div>
        <div class="actions">
          <%= f.submit class: 'btn btn-primary' %>
    <% end %>
    </div>

    <p>Have been user? <%= link_to "Sign in now!", login_path %></p>
  </div>
</div>

app/views/users/_user_profile.html.erb
<div class="banner-user row">
  <img src="http://rockymountainnationalpark.com/sites/all/themes/rmnp/images/bugling-elk-rocky-mountain-national-park.jpg" alt="banner">
  <%= link_to 'change image banner', '#', class: 'change-image' %>
</div>
<div class="user-info row">
  <div class="col col-md-4 div-border-right">
    <div class="user-avatar col-md-4">
      <%= image_tag(user.avatar_url) %>
    </div>
    <div class="user-name col-md-8">
      <%= render 'follow_button', user: user %>
      <p><%= link_to user.name, user_path(user) %></p>
      <%= user.total_images.to_s + ' photos | ' + user.count_followers.to_s + ' follow' %>
    </div>
  </div>
  <div class="col col-md-4 div-border-right">
    <h4>Equipment</h4>
    <h5>Camera</h5>
    <h5>Len</h5>
  </div>
  <div class="col col-md-4">
    <h4>Recent Activitys</h4>
    <h5>Collected yutaka.miura.503's photo</h5>
    <h5>Collected yutaka.miura.503's photo</h5>
  </div>
</div>

app/views/users/about.html.erb
<div class="top-layout-user row">
  <%= render 'user_profile', user: @user %>
  <div class="user-member row">
    <ul class="nav nav-tabs" role="tablist">
      <li><a href="<%= user_url(@user) %>">Photo Spots</a></li>
      <li><a href="<%= collection_user_url(@user) %>">Collection</a></li>
      <li class="active"><a href="<%= about_user_url(@user) %>">About</a></li>
      <li><a href="<%= followers_user_url(@user) %>">Followers</a></li>
      <li><a href="<%= followings_user_url(@user) %>">Followings</a></li>
    </ul>
  </div>
</div>

<div class="user-about row">
  <div class="user-information col col-md-6">
    <div class="row">
      <div class="user-element">Experience</div>
      Pashadelic member since 2016
    </div>
    <div class="row">
      <div class="user-element">Biography</div>
      The information hasn't been provided yet.
    </div>
    <div class="row">
      <div class="user-element">Interests</div>
      The information hasn't been provided yet.
    </div>
  </div>

  <div class="user-equipment col col-md-6">
    <h3>What you have in common</h3>
    <%= image_tag(@user.avatar_url) %>
    <div class="user-element">Equipment</div>
    <div class="user-element">Camera:</div>
    <div class="user-element">Lens:</div>
    <div class="user-element">Tripod:</div>
    <div class="user-element">Filter:</div>
    <div class="user-element">Software:</div>
  </div>
</div>

app/views/users/collection.html.erb
<div class="top-layout-user row">
  <%= render 'user_profile', user: @user %>
  <div class="user-member row">
    <ul class="nav nav-tabs" role="tablist">
      <li><a href="<%= user_url(@user) %>">Photo Spots</a></li>
      <li class="active"><a href="<%= collection_user_url(@user) %>">Collection</a></li>
      <li><a href="<%= about_user_url(@user) %>">About</a></li>
      <li><a href="<%= followers_user_url(@user) %>">Followers</a></li>
      <li><a href="<%= followings_user_url(@user) %>">Followings</a></li>
    </ul>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/follow.js.erb
$('#follow-button-<%= @user.id %>').replaceWith("<%= j render 'follow_button', user: @user %>");

app/views/users/followers.html.erb
<div class="top-layout-user row">
  <%= render 'user_profile', user: @user %>
  <div class="user-member row">
    <ul class="nav nav-tabs" role="tablist">
      <li><a href="<%= user_url(@user) %>">Photo Spots</a></li>
      <li><a href="<%= collection_user_url(@user) %>">Collection</a></li>
      <li><a href="<%= about_user_url(@user) %>">About</a></li>
      <li class="active"><a href="<%= followers_user_url(@user) %>">Followers</a></li>
      <li><a href="<%= followings_user_url(@user) %>">Followings</a></li>
    </ul>
  </div>
</div>

<%= render 'follower_list', users: followers_users_list(@followers) %>

app/views/users/followings.html.erb
<div class="top-layout-user row">
  <%= render 'user_profile', user: @user %>
  <div class="user-member row">
    <ul class="nav nav-tabs" role="tablist">
      <li><a href="<%= user_url(@user) %>">Photo Spots</a></li>
      <li><a href="<%= collection_user_url(@user) %>">Collection</a></li>
      <li><a href="<%= about_user_url(@user) %>">About</a></li>
      <li><a href="<%= followers_user_url(@user) %>">Followers</a></li>
      <li class="active"><a href="<%= followings_user_url(@user) %>">Followings</a></li>
    </ul>
  </div>
</div>

<%= render 'follower_list', users: followings_users_list(@followings) %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Email</th>
      <th>Password digest</th>
      <th>Visible</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.visible %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1 style="text-align: center">Sign Up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="top-layout-user row">
  <%= render 'user_profile', user: @user %>
  <div class="user-member row">
    <ul class="nav nav-tabs" role="tablist">
      <li class="active"><a href="<%= user_url(@user) %>">Photo Spots</a></li>
      <li><a href="<%= collection_user_url(@user) %>">Collection</a></li>
      <li><a href="<%= about_user_url(@user) %>">About</a></li>
      <li><a href="<%= followers_user_url(@user) %>">Followers</a></li>
      <li><a href="<%= followings_user_url(@user) %>">Followings</a></li>
    </ul>
  </div>
</div>

<div class="body-layout-user row">
  <% @images.each do |image| %>
      <div class="row col-md-3">
        <div class="user-images" id="user-image-<%= image.id %>">
          <%= image_tag image.img_url.thumb.url %>
          <div class="user-img-info" id="user-img-<%= image.id %>">
            <%= 'uploaded' + image.created_at.strftime(" %H:%m %a, %d %b %Y") %> <br>
            <i class="fa fa-folder-o"></i><%= '0 collect' %> <br>
            <i class="fa fa-thumbs-o-up"></i><%= image.total_like.to_s + ' like' %> <br>
            <i class="fa fa-comment"></i><%= image.total_comment.to_s + ' comment' %>
            <div class="user-img-action">
              <%= link_to 'Edit', edit_image_path(image) %>
              <%= link_to 'View', image_path(image) %>
            </div>
          </div>
        </div>
      </div>
      <script>
        $('#user-image-<%= image.id %>').hover(function(){
          $('.user-img-info').hide();
          $('#user-img-<%= image.id %>').show();
        });
        $('body').hover(function(){
          $('.user-img-info').hide();
        });
      </script>
  <% end %>
</div>