config/routes.rb
Rails.application.routes.draw do
  resources :images do
    member do
      get 'like' => 'images#like'
    end
  end

  get 'search' => 'images#search'
  resources :categories
  resources :users do
    member do
      get 'follow' => 'users#follow'
      get 'collection' => 'users#collection'
      get 'about' => 'users#about'
      get 'followers' => 'users#followers'
      get 'followings' => 'users#followings'
    end
  end
  resources :comments, only: [:create] do
    member do
      get 'reply', to: 'comments#new_reply'
      post 'reply', to: 'comments#create_reply'
    end
  end

  root 'welcome#popular'
  get 'popular' => 'welcome#popular'
  get 'upcoming' => 'welcome#upcoming'
  get 'photos_of_days' => 'welcome#photos_of_days'
  get 'photos_of_months' => 'welcome#photos_of_months'

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def popular
    @images = Image.created_at_asc
  end

  def upcoming
    @images = Image.created_at_desc
  end

  def photos_of_days
  end

  def photos_of_months
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h1>HELLO!!! Today, How are you</h1>

app/views/welcome/photos_of_days.html.erb
<div class="row">
  <ul class="nav nav-pills">
    <li><a href="<%= popular_url %>">Popular</a></li>
    <li><a href="<%= upcoming_url %>">Upcoming</a></li>
    <li class="active"><a href="<%= photos_of_days_url %>">Photo of days</a></li>
    <li><a href="<%= photos_of_months_url %>">Photo of month</a></li>
  </ul>
</div>

<%= render 'categories/image_frame', images: photos_of_days %>

app/views/welcome/photos_of_months.html.erb
<div class="row">
  <ul class="nav nav-pills">
    <li><a href="<%= popular_url %>">Popular</a></li>
    <li><a href="<%= upcoming_url %>">Upcoming</a></li>
    <li><a href="<%= photos_of_days_url %>">Photo of days</a></li>
    <li class="active"><a href="<%= photos_of_months_url %>">Photo of month</a></li>
  </ul>
</div>

<%= render 'categories/image_frame', images: photos_of_months %>

app/views/welcome/popular.html.erb
<div class="row">
  <ul class="nav nav-pills">
    <li class="active"><a href="<%= popular_url %>">Popular</a></li>
    <li><a href="<%= upcoming_url %>">Upcoming</a></li>
    <li><a href="<%= photos_of_days_url %>">Photo of days</a></li>
    <li><a href="<%= photos_of_months_url %>">Photo of month</a></li>
  </ul>
</div>

<%= render 'categories/image_frame', images: @images %>

app/views/welcome/upcoming.html.erb
<div class="row">
  <ul class="nav nav-pills">
    <li><a href="<%= popular_url %>">Popular</a></li>
    <li class="active"><a href="<%= upcoming_url %>">Upcoming</a></li>
    <li><a href="<%= photos_of_days_url %>">Photo of days</a></li>
    <li><a href="<%= photos_of_months_url %>">Photo of month</a></li>
  </ul>
</div>

<%= render 'categories/image_frame', images: @images %>