config/routes.rb
Rails.application.routes.draw do
  resources :images do
    member do
      get 'like' => 'images#like'
    end
  end

  get 'search' => 'images#search'
  resources :categories
  resources :users do
    member do
      get 'follow' => 'users#follow'
      get 'collection' => 'users#collection'
      get 'about' => 'users#about'
      get 'followers' => 'users#followers'
      get 'followings' => 'users#followings'
    end
  end
  resources :comments, only: [:create] do
    member do
      get 'reply', to: 'comments#new_reply'
      post 'reply', to: 'comments#create_reply'
    end
  end

  root 'welcome#popular'
  get 'popular' => 'welcome#popular'
  get 'upcoming' => 'welcome#upcoming'
  get 'photos_of_days' => 'welcome#photos_of_days'
  get 'photos_of_months' => 'welcome#photos_of_months'

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :img_url, ImageUploader

  belongs_to :category
  belongs_to :user
  has_many :comments
  has_many :liked

  validate :image_size_validation

  scope :created_at_desc, -> {order('created_at DESC')}
  scope :created_at_asc, -> {order('created_at ASC')}

  def total_like
    self.liked.count
  end

  def total_comment
    self.comments.count
  end

  def direct_children_comments(level, parent_id)
    @comments = self.comments.select { |comment| comment.level == level && comment.parent_id == parent_id }
  end

  private
  def image_size_validation
    errors[:image] << "should be less than 40MB" if img_url.size > 40.megabytes
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy, :like]

  def index
    @images = Image.all
  end

  def show
  end

  def new
    @image = Image.new
  end

  def edit
  end

  def create
    @image = Image.new(image_params)
    if current_user
      @image.user = current_user
    end

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
    end
  end

  def search
    @query = params[:query]
    @images = Image.where('description LIKE ?', "%#{params[:query]}%").paginate(:page => params[:page], :per_page => 9)
  end

  def like
    respond_to do |format|
      if current_user
        if Liked.where(user: current_user, image: @image).count > 0
          Liked.where(user: current_user, image: @image).first.destroy
        else
          Liked.create(user: current_user, image: @image)
        end
        format.js
      else
        format.js {render inline: 'sorry, you must sign in to like!!!'}
      end
    end
  end

  private
  def set_image
    @image = Image.find(params[:id])
  end

  def image_params
    params.require(:image).permit(:category_id, :img_url, :description)
  end
end

app/helpers/images_helper.rb
module ImagesHelper
  def six_images(user)
    Image.where(user: user).last(6)
  end

  def photos_of_days
    photos = []
    if Image.first
      time1 = Image.first.created_at.beginning_of_day
      time2 = (Image.last.created_at + 1.day).beginning_of_day
      while time1 < time2
        photos << Image.where(created_at: time1..(time1 + 1.day)).sort{ |l,r| r.liked.count <=> l.liked.count }.first
        time1 = time1 + 1.day
      end
    end
    photos
  end

  def photos_of_months
    photos = []
    if Image.first
      time1 = Image.first.created_at.beginning_of_month
      time2 = (Image.last.created_at + 1.month).beginning_of_month
      while time1 < time2
        photos << Image.where(created_at: time1..(time1 + 1.month)).sort{ |l,r| r.liked.count <=> l.liked.count }.first
        time1 = time1 + 1.month
      end
    end
    photos
  end
end

app/views/images/_form.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_for(@image) do |f| %>
        <div class="field">
          <%= f.label :category_id %><br>
          <%= f.collection_select :category_id, Category.all,:id,:name, include_blank: true, class: 'form-control' %>
        </div>
        <div class="field">
          <%= f.label :description %><br>
          <%= f.text_field :description, class: 'form-control' %>
        </div>
        <div class="field">
          <%= f.label :img_url %><br>
          <%= f.file_field :img_url, class: 'form-control' %>
        </div>
        <div class="actions">
          <%= f.submit class: 'btn btn-primary' %>
        </div>
    <% end %>
  </div>
</div>

app/views/images/_image_button_like.html.erb
<div class="image-button-like" id="image-button-like-<%= image.id %>">
  <% if current_user %>
      <%= link_to ('<i class="fa fa-thumbs-up ' + current_user.liked?(image).to_s + '"></i>').html_safe, like_image_path(image), remote: true %>
  <% else %>
      <%= ('<i class="fa fa-thumbs-up false"></i>').html_safe %>
  <% end %>
</div>

app/views/images/_image_statistical.html.erb
<div class="image-statistical" id="image-statistical-<%= image.id %>">
  <i class="fa fa-thumbs-o-up"></i><%= image.total_like %>
  <i class="fa fa-comments-o"></i><%= image.total_comment %>
</div>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>User</th>
      <th>Img url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.category %></td>
        <td><%= image.user %></td>
        <td><%= image.img_url %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/like.js.erb
$("#image-statistical-<%= @image.id %>").replaceWith("<%= j (render 'images/image_statistical', image: @image) %>");
$("#image-button-like-<%= @image.id %>").replaceWith("<%= j (render 'images/image_button_like', image: @image) %>");

app/views/images/new.html.erb
<h1 style="text-align: center">New Image</h1>

<%= render 'form' %>

app/views/images/search.html.erb
<h3><%='Found for: ' + @query %></h3>
<div class="list-images-result row">
  <% @images.each do |image| %>
      <div class="image-result col col-md-3" id="image-result-<%= image.id %>">
        <%= image_tag(image.img_url.thumb.url) %>
        <div class="location-image" id="location-image-<%= image.id %>">
          <span><%= render 'images/image_button_like', image: image %></span>
          <%= image.description %>
        </div>
      </div>
      <script>
        $('#image-result-<%= image.id %>').mouseenter(function(){
          $('#location-image-<%= image.id %>').show(300);
        });
      </script>
  <% end %>
</div>

<script>
  $('.image-result').mouseleave(function(){
    $('.location-image').hide(300);
  });
</script>

app/views/images/show.html.erb
<div class="row">
  <div class="image-content">
    <%= image_tag(@image.img_url) %>
  </div>
  <div class="image-info">
    <div class="col col-md-8">
      <% if current_user %>
          <div class="comment-form row">
            <div class="user-avatar">
              <%= image_tag(current_user.avatar_url) %>
            </div>
            <div class="form-comment">
              <%= form_for(Comment.new, :url => {controller: 'comments', action: 'create', user: current_user, image: @image}, remote: true) do |f| %>
                  <div class="field">
                    <%= f.text_area :content, placeholder: 'Add your comment...' %>
                  </div>
                  <div class="actions">
                    <%= f.submit 'Comment' %>
                  </div>
              <% end %>
            </div>
          </div>
      <% end %>
      <% @image.comments.level_0.each do |comment| %>
          <%= render comment %>
      <% end %>
    </div>

    <div class="col col-md-4">

    </div>
  </div>
</div>

<script>
  $('.image-content').click(function(){
    if($('.image-content').css("position") == 'static') {
      $('.image-content').css({
        "min-height": "100vh",
        "min-width": "100vh",
        "position": "absolute",
        "padding-top": "100px",
        "left": "0",
        "top": "0"
      });
      $('.image-content img').css({
        "margin": "auto auto",
      });
    }
    else {
      $('.image-content').css({
        "min-height": "auto",
        "width": "100%",
        "margin": "0 auto",
        "position": "static",
        "padding-top": "0",
        "left": "0",
        "top": "0"
      });
    }
  });
</script>