config/routes.rb
Rails.application.routes.draw do
  resources :images do
    member do
      get 'like' => 'images#like'
    end
  end

  get 'search' => 'images#search'
  resources :categories
  resources :users do
    member do
      get 'follow' => 'users#follow'
      get 'collection' => 'users#collection'
      get 'about' => 'users#about'
      get 'followers' => 'users#followers'
      get 'followings' => 'users#followings'
    end
  end
  resources :comments, only: [:create] do
    member do
      get 'reply', to: 'comments#new_reply'
      post 'reply', to: 'comments#create_reply'
    end
  end

  root 'welcome#popular'
  get 'popular' => 'welcome#popular'
  get 'upcoming' => 'welcome#upcoming'
  get 'photos_of_days' => 'welcome#photos_of_days'
  get 'photos_of_months' => 'welcome#photos_of_months'

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/views/layouts/_footer.html.erb
<div class="row" style="height: 200px; background-color: white;margin-top: 50px;font-size: 150px;text-align: center;">
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top my-nav">
  <div class="container clearfix">
    <div class="my-navbar-left">
      <a href="<%= root_path %>">
        <div class="logo"><img src="http://assets.pashadelic.com/assets/common/pashadelic_logo.png"></div>
      </a>
      <div class="search-form">
        <%= form_tag search_path, method: :get do %>
            <i class="fa fa-picture-o"></i>
            <%= text_field_tag :query, params[:query], placeholder: 'Find inspiring photos' %>
            <button type="submit">
              <i class="fa fa-search"></i>
            </button>
        <% end %>
      </div>
    </div>

    <div class="nav navbar-nav my-navbar-right">
      <% if current_user %>
          <%= link_to '<i class="fa fa-upload"></i>'.html_safe, new_image_path, class: 'icon-upload' %>
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-user icon-upload"></i><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<%= user_url(current_user) %>">My page</a></li>
            <li><a href="#">Setting</a></li>
            <li><%= link_to 'Logout', logout_url, method: :delete %></li>
          </ul>
      <% else %>
          <%= link_to '<i class="fa fa-user-plus"></i>'.html_safe, new_user_path, class: 'icon-upload' %>
          <%= link_to '<i class="fa fa-sign-in"></i>'.html_safe, login_path, class: 'icon-upload' %>
      <% end %>
    </div>
  </div>
</div>

<div class="main-manu" style="margin-top: 60px">
  <div class="menu-tab">
    <%= link_to 'Home', root_path %>
  </div>
  <div class="menu-tab">
    <%= link_to 'Photos', popular_path %>
  </div>
  <div class="menu-tab">
    <%= link_to 'Categories', categories_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pashadelic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
<%= render 'layouts/header' %>
<div class="margin-nav"></div>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>